/*******************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2025
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


#include "cy_pdl.h"
#include "cybsp.h"
#include "cygfx_defines.h"
#include "cygfx_basetypes.h"
#include "cy_fpdlink.h"
#include "cy_gfx_env.h"
#include "platform_irq.h"
#include "cmsis_compiler.h"


/*******************************************************************************
* Macros
********************************************************************************/

/*******************************************************************************
* Function Prototypes
********************************************************************************/

/*******************************************************************************
* Global Variables
********************************************************************************/

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This main achieve the Initialization setting for graphics environment as 
* commonly setting.
*
* Also enable the PD and interrupt for graphics.
*
* Return: int
*
*******************************************************************************/
int main(void)
{
    /* Initialize the device and board peripherals */
    cybsp_init() ;
    
    /* Initializes the GFX environment with most commonly used settings. */
    Cy_GfxEnv_FastInit(0, 0, NULL);
    
    /* Enable Graphics Subsystem Power Switch */
    Cy_PD_Enable();
    
    /* Enable global interrupts. */
    __enable_irq();
    
    /* Enable the interrupt for Videoss */
    ConfigureVideoSSInterrupt();
    
    /* Please add the user code as below */

    for (;;)
    {
        Cy_GPIO_Inv(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
        Cy_SysLib_Delay(250);
    }
}

/* [] END OF FILE */
